/* Localized step catalog is kept outside page component to avoid in-page hardcoded locale blocks. */

export const quizStepsRu = [
  {
    step: 1,
    type: "single-selection-with-image",
    question: "Что вы ищете?",
    uiTag: "main-goal",
    answers: [
      {
        image: "/images/quiz/quiz-affemity-funnel/q-1-1.webp",
        svgIcon: "/icons/quiz/quiz-affemity-funnel/q-1-1-icon.svg",
        svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-1-1-iconActive.svg",
        title: "Серьёзные отношения",
      },
      {
        image: "/images/quiz/quiz-affemity-funnel/q-1-2.webp",
        svgIcon: "/icons/quiz/quiz-affemity-funnel/q-1-2-icon.svg",
        svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-1-2-iconActive.svg",
        title: "Случайные свидания",
      },
      {
        image: "/images/quiz/quiz-affemity-funnel/q-1-3.webp",
        svgIcon: "/icons/quiz/quiz-affemity-funnel/q-1-3-icon.svg",
        svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-1-3-iconActive.svg",
        title: "Новые знакомства",
      },
      {
        image: "/images/quiz/quiz-affemity-funnel/q-1-4.webp",
        svgIcon: "/icons/quiz/quiz-affemity-funnel/q-1-4-icon.svg",
        svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-1-4-iconActive.svg",
        title: "Ещё определяюсь",
      },
    ],
  },
  { step: 2, type: "single", question: "Сколько вам лет?", answers: ["18 - 24", "25 - 34", "35 - 44", "45 - 54", "55 +"], uiTag: "qAge" },
  {
    step: 3,
    type: "single-selection-with-svg",
    question: "Как бы вы описали свою личность?",
    uiTag: "your-personality",
    answers: [
      { title: "Интроверт", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-3-1-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-3-1-iconActive.svg" },
      { title: "Экстраверт", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-3-2-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-3-2-iconActive.svg" },
      { title: "И то, и другое", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-3-3-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-3-3-iconActive.svg" },
      { title: "Не уверен", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-3-4-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-3-4-iconActive.svg" },
    ],
  },
  {
    step: 4,
    type: "single",
    question: "На каком этапе вашего пути знакомств вы находитесь?",
    answers: ["Почти живу жизнью моей мечты в отношениях", "Добиваюсь прогресса", "Только начинаю"],
  },
  { step: 5, type: "prompt-1" },
  {
    step: 6,
    type: "multiple",
    question: "Какие навыки вы бы хотели улучшить?",
    description: "Выберите все подходящие варианты",
    uiTag: "skills-to-improve",
    answers: [
      { title: "Секреты привлекательности", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-6-1-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-6-1-iconActive.svg" },
      { title: "Уверенная переписка", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-6-2-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-6-2-iconActive.svg" },
      { title: "Советы по флирту", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-6-3-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-6-3-iconActive.svg" },
      { title: "Развитие уверенности в себе", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-6-4-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-6-4-iconActive.svg" },
      { title: "Начало разговоров", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-6-5-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-6-5-iconActive.svg" },
    ],
  },
  { step: 7, type: "prompt-2" },
  {
    step: 8,
    type: "single-rate",
    statement: "Я предпочитаю, чтобы мои сообщения были лёгкими и непринуждёнными",
    question: "Насколько это утверждение описывает вас?",
    answers: [
      { answer: 1, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike-active.svg" },
      { answer: 2, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike-active.svg" },
      { answer: 3, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-dont-know.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-dont-know-active.svg" },
      { answer: 4, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-like-active.svg" },
      { answer: 5, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-like-active.svg" },
    ],
  },
  {
    step: 9,
    type: "single-rate",
    statement: "Мне сложно справляться с отказом",
    question: "Насколько это утверждение описывает вас?",
    answers: [
      { answer: 1, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike-active.svg" },
      { answer: 2, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike-active.svg" },
      { answer: 3, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-dont-know.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-dont-know-active.svg" },
      { answer: 4, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-like-active.svg" },
      { answer: 5, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-like-active.svg" },
    ],
  },
  { step: 10, type: "slide", question: "Насколько важно для вас, чтобы женщина проявляла интерес с самого начала?", description: "Пожалуйста, выберите уровень важности" },
  { step: 11, type: "prompt-3" },
  {
    step: 12,
    type: "single-rate",
    statement: "Я склонен сразу рассказывать о своих потребностях",
    question: "Насколько это утверждение описывает вас?",
    answers: [
      { answer: 1, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike-active.svg" },
      { answer: 2, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike-active.svg" },
      { answer: 3, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-dont-know.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-dont-know-active.svg" },
      { answer: 4, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-like-active.svg" },
      { answer: 5, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-like-active.svg" },
    ],
  },
  {
    step: 13,
    type: "single-selection-with-svg",
    question: "Вам сложно поддерживать разговор?",
    answers: [
      { title: "Да", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-likeActive.svg" },
      { title: "Нет", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-dislikeActive.svg" },
      { title: "Не уверен", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-dont-know.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-dont-knowActive.svg" },
    ],
  },
  {
    step: 14,
    type: "single-selection-with-svg",
    question: "Как быстро вы обычно отвечаете женщине, которая вам интересна?",
    answers: [
      { title: "Сразу же", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-15-1-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-15-1-iconActive.svg" },
      { title: "Немного жду", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-15-2-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-15-2-iconActive.svg" },
    ],
  },
  { step: 15, type: "prompt-4" },
  {
    step: 16,
    type: "single-selection-with-svg",
    question: "Вы легко читаете между строк, когда она пишет?",
    answers: [
      { title: "Да", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-likeActive.svg" },
      { title: "Нет", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-dislikeActive.svg" },
    ],
  },
  {
    step: 17,
    type: "single-rate",
    statement: "Мне комфортно выражать свои эмоции",
    question: "Насколько это утверждение описывает вас?",
    answers: [
      { answer: 1, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-dislike-active.svg" },
      { answer: 2, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-dislike-active.svg" },
      { answer: 3, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-dont-know.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-dont-know-active.svg" },
      { answer: 4, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-small-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-small-like-active.svg" },
      { answer: 5, svgIcon: "/icons/quiz/quiz-affemity-funnel/rate-big-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/rate-big-like-active.svg" },
    ],
  },
  {
    step: 18,
    type: "single-selection-with-svg",
    question: "Вы когда-нибудь специально откладывали ответ?",
    answers: [
      { title: "Да", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-likeActive.svg" },
      { title: "Нет", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-dislikeActive.svg" },
    ],
  },
  {
    step: 19,
    type: "single-selection-with-svg",
    question: "Вас когда-нибудь игнорировали после свидания?",
    uiTag: "have-been-ghosted",
    answers: [
      { title: "Да", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-like.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-likeActive.svg" },
      { title: "Нет", svgIcon: "/icons/quiz/quiz-affemity-funnel/single-dislike.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/single-dislikeActive.svg" },
    ],
  },
  { step: 20, type: "prompt-5" },
  { step: 21, type: "slide", question: "Насколько важно для вас сейчас улучшить свою личную жизнь?", description: "Пожалуйста, выберите уровень важности" },
  { step: 22, type: "prompt-6" },
  {
    step: 23,
    type: "single-selection-with-svg",
    question: "Сколько времени вы готовы вкладывать в улучшение навыков знакомств?",
    uiTag: "daily-learning-goal",
    answers: [
      { title: "< 5 минут/день", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-24-1-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-24-1-iconActive.svg" },
      { title: "5 - 10 минут/день", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-24-2-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-24-2-iconActive.svg" },
      { title: "10 - 30 минут/день", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-24-3-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-24-3-iconActive.svg" },
      { title: "> 30 минут/день", svgIcon: "/icons/quiz/quiz-affemity-funnel/q-24-4-icon.svg", svgIconActive: "/icons/quiz/quiz-affemity-funnel/q-24-4-iconActive.svg" },
    ],
  },
  { step: 24, type: "prompt-7" },
  { step: 25, type: "calculating-screen" },
  { step: 26, type: "result-screen" },
];
