"""init

Revision ID: ab442adc716d
Revises:
Create Date: 2026-03-16 07:56:03.488240

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab442adc716d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_user_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "telegram_user_id", name="uq_access_order_telegram"
        ),
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_access_bindings_order_id"),
        "access_bindings",
        ["order_id"],
        unique=False,
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_access_bindings_telegram_user_id"),
        "access_bindings",
        ["telegram_user_id"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revoked_reason", sa.String(length=128), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_access_tokens_order_id"),
        "access_tokens",
        ["order_id"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "bot_context_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("batch_no", sa.Integer(), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("parse_confidence", sa.Float(), nullable=False),
        sa.Column("needs_confirmation", sa.Boolean(), nullable=False),
        sa.Column("role_ambiguity", sa.Boolean(), nullable=False),
        sa.Column("summary_for_user", sa.Text(), nullable=False),
        sa.Column(
            "extraction_meta",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        "ix_bot_context_assets_session_batch_created",
        "bot_context_assets",
        ["session_id", "batch_no", "created_at"],
        unique=False,
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_bot_context_assets_session_id"),
        "bot_context_assets",
        ["session_id"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "bot_generation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "request_payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "response_payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("llm_provider", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_bot_generation_runs_session_id"),
        "bot_generation_runs",
        ["session_id"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "bot_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("telegram_user_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_batch_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        "ix_bot_sessions_user_status",
        "bot_sessions",
        ["telegram_user_id", "status"],
        unique=False,
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_bot_sessions_telegram_user_id"),
        "bot_sessions",
        ["telegram_user_id"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "http_request_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("query_string", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("client_ip", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "request_headers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column(
            "response_headers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error_class", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        "ix_http_request_logs_created_at",
        "http_request_logs",
        ["created_at"],
        unique=False,
        schema="flirto",
    )
    op.create_index(
        "ix_http_request_logs_request_id",
        "http_request_logs",
        ["request_id"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "mobi_slon_request_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("transport", sa.String(length=32), nullable=False),
        sa.Column("incoming_path", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("clickid", sa.String(length=256), nullable=True),
        sa.Column("session_id", sa.String(length=256), nullable=True),
        sa.Column("page_path", sa.Text(), nullable=True),
        sa.Column(
            "tracking_params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "request_headers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("raw_body", sa.Text(), nullable=True),
        sa.Column(
            "validation_errors",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("accepted", sa.Boolean(), nullable=True),
        sa.Column("forwarded", sa.Boolean(), nullable=True),
        sa.Column("upstream_url", sa.Text(), nullable=True),
        sa.Column(
            "upstream_params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("upstream_status_code", sa.Integer(), nullable=True),
        sa.Column("upstream_response_body", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_class", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        "ix_mobi_slon_request_logs_created_at",
        "mobi_slon_request_logs",
        ["created_at"],
        unique=False,
        schema="flirto",
    )
    op.create_index(
        "ix_mobi_slon_request_logs_request_id",
        "mobi_slon_request_logs",
        ["request_id"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("brand", sa.String(length=64), nullable=True),
        sa.Column("landing_id", sa.String(length=128), nullable=True),
        sa.Column("entry_host", sa.String(length=255), nullable=True),
        sa.Column("entry_path", sa.String(length=1024), nullable=True),
        sa.Column("clickid", sa.String(length=128), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("plan", sa.String(length=64), nullable=False),
        sa.Column("promo_code", sa.String(length=64), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("fulfillment_status", sa.String(length=32), nullable=False),
        sa.Column("access_status", sa.String(length=32), nullable=False),
        sa.Column("stripe_session_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=128), nullable=True),
        sa.Column(
            "stripe_current_period_end", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_session_id"),
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_orders_email"),
        "orders",
        ["email"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "payment_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("stripe_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("process_result", sa.String(length=32), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_payment_events_stripe_event_id"),
        "payment_events",
        ["stripe_event_id"],
        unique=True,
        schema="flirto",
    )
    op.create_table(
        "promo_offers",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()::text"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("sub_weekly_amount_minor", sa.Integer(), nullable=False),
        sa.Column("sub_monthly_amount_minor", sa.Integer(), nullable=False),
        sa.Column("sub_yearly_amount_minor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_promo_offers_code"),
        "promo_offers",
        ["code"],
        unique=True,
        schema="flirto",
    )
    op.create_table(
        "quiz_sessions",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()::text"),
            nullable=False,
        ),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("brand", sa.String(length=64), nullable=True),
        sa.Column("landing_id", sa.String(length=128), nullable=True),
        sa.Column("entry_host", sa.String(length=255), nullable=True),
        sa.Column("entry_path", sa.String(length=1024), nullable=True),
        sa.Column("clickid", sa.String(length=128), nullable=False),
        sa.Column(
            "tracking_params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "answers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("checkout_state", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        "ix_quiz_sessions_clickid",
        "quiz_sessions",
        ["clickid"],
        unique=False,
        schema="flirto",
    )
    op.create_index(
        "ix_quiz_sessions_created_at",
        "quiz_sessions",
        ["created_at"],
        unique=False,
        schema="flirto",
    )
    op.create_table(
        "restore_otps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("otp_hash", sa.String(length=128), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_restore_otps_email"),
        "restore_otps",
        ["email"],
        unique=False,
        schema="flirto",
    )
    op.create_index(
        op.f("ix_flirto_restore_otps_otp_hash"),
        "restore_otps",
        ["otp_hash"],
        unique=False,
        schema="flirto",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_flirto_restore_otps_otp_hash"),
        table_name="restore_otps",
        schema="flirto",
    )
    op.drop_index(
        op.f("ix_flirto_restore_otps_email"), table_name="restore_otps", schema="flirto"
    )
    op.drop_table("restore_otps", schema="flirto")
    op.drop_index(
        "ix_quiz_sessions_created_at", table_name="quiz_sessions", schema="flirto"
    )
    op.drop_index(
        "ix_quiz_sessions_clickid", table_name="quiz_sessions", schema="flirto"
    )
    op.drop_table("quiz_sessions", schema="flirto")
    op.drop_index(
        op.f("ix_flirto_promo_offers_code"), table_name="promo_offers", schema="flirto"
    )
    op.drop_table("promo_offers", schema="flirto")
    op.drop_index(
        op.f("ix_flirto_payment_events_stripe_event_id"),
        table_name="payment_events",
        schema="flirto",
    )
    op.drop_table("payment_events", schema="flirto")
    op.drop_index(op.f("ix_flirto_orders_email"), table_name="orders", schema="flirto")
    op.drop_table("orders", schema="flirto")
    op.drop_index(
        "ix_mobi_slon_request_logs_request_id",
        table_name="mobi_slon_request_logs",
        schema="flirto",
    )
    op.drop_index(
        "ix_mobi_slon_request_logs_created_at",
        table_name="mobi_slon_request_logs",
        schema="flirto",
    )
    op.drop_table("mobi_slon_request_logs", schema="flirto")
    op.drop_index(
        "ix_http_request_logs_request_id",
        table_name="http_request_logs",
        schema="flirto",
    )
    op.drop_index(
        "ix_http_request_logs_created_at",
        table_name="http_request_logs",
        schema="flirto",
    )
    op.drop_table("http_request_logs", schema="flirto")
    op.drop_index(
        op.f("ix_flirto_bot_sessions_telegram_user_id"),
        table_name="bot_sessions",
        schema="flirto",
    )
    op.drop_index(
        "ix_bot_sessions_user_status", table_name="bot_sessions", schema="flirto"
    )
    op.drop_table("bot_sessions", schema="flirto")
    op.drop_index(
        op.f("ix_flirto_bot_generation_runs_session_id"),
        table_name="bot_generation_runs",
        schema="flirto",
    )
    op.drop_table("bot_generation_runs", schema="flirto")
    op.drop_index(
        op.f("ix_flirto_bot_context_assets_session_id"),
        table_name="bot_context_assets",
        schema="flirto",
    )
    op.drop_index(
        "ix_bot_context_assets_session_batch_created",
        table_name="bot_context_assets",
        schema="flirto",
    )
    op.drop_table("bot_context_assets", schema="flirto")
    op.drop_index(
        op.f("ix_flirto_access_tokens_order_id"),
        table_name="access_tokens",
        schema="flirto",
    )
    op.drop_table("access_tokens", schema="flirto")
    op.drop_index(
        op.f("ix_flirto_access_bindings_telegram_user_id"),
        table_name="access_bindings",
        schema="flirto",
    )
    op.drop_index(
        op.f("ix_flirto_access_bindings_order_id"),
        table_name="access_bindings",
        schema="flirto",
    )
    op.drop_table("access_bindings", schema="flirto")
    # ### end Alembic commands ###
