"""add promo

Revision ID: 657dcb459b3d
Revises: 81b659327def
Create Date: 2026-03-09 16:11:45.330514

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "657dcb459b3d"
down_revision: Union[str, Sequence[str], None] = "81b659327def"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promo_offers",
        sa.Column(
            "id",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()::text"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("sub_weekly_amount_minor", sa.Integer(), nullable=False),
        sa.Column("sub_monthly_amount_minor", sa.Integer(), nullable=False),
        sa.Column("sub_quarterly_amount_minor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_promo_offers_code"),
        "promo_offers",
        ["code"],
        unique=True,
        schema="seranking",
    )
    op.add_column(
        "orders", sa.Column("promo_code", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "promo_code")
    op.drop_index(
        op.f("ix_seranking_promo_offers_code"),
        table_name="promo_offers",
        schema="seranking",
    )
    op.drop_table("promo_offers", schema="seranking")
    # ### end Alembic commands ###
