"""add logging

Revision ID: 81b659327def
Revises: b7871b2cd2c3
Create Date: 2026-03-09 12:23:32.610516

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81b659327def"
down_revision: Union[str, Sequence[str], None] = "b7871b2cd2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "http_request_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("query_string", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("client_ip", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "request_headers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column(
            "response_headers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error_class", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="seranking",
    )
    op.create_index(
        "ix_http_request_logs_created_at",
        "http_request_logs",
        ["created_at"],
        unique=False,
        schema="seranking",
    )
    op.create_index(
        "ix_http_request_logs_request_id",
        "http_request_logs",
        ["request_id"],
        unique=False,
        schema="seranking",
    )
    op.create_table(
        "mobi_slon_request_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("transport", sa.String(length=32), nullable=False),
        sa.Column("incoming_path", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("clickid", sa.String(length=256), nullable=True),
        sa.Column("session_id", sa.String(length=256), nullable=True),
        sa.Column("page_path", sa.Text(), nullable=True),
        sa.Column(
            "tracking_params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "request_headers",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("raw_body", sa.Text(), nullable=True),
        sa.Column(
            "validation_errors",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("accepted", sa.Boolean(), nullable=True),
        sa.Column("forwarded", sa.Boolean(), nullable=True),
        sa.Column("upstream_url", sa.Text(), nullable=True),
        sa.Column(
            "upstream_params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("upstream_status_code", sa.Integer(), nullable=True),
        sa.Column("upstream_response_body", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_class", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="seranking",
    )
    op.create_index(
        "ix_mobi_slon_request_logs_created_at",
        "mobi_slon_request_logs",
        ["created_at"],
        unique=False,
        schema="seranking",
    )
    op.create_index(
        "ix_mobi_slon_request_logs_request_id",
        "mobi_slon_request_logs",
        ["request_id"],
        unique=False,
        schema="seranking",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_mobi_slon_request_logs_request_id",
        table_name="mobi_slon_request_logs",
        schema="seranking",
    )
    op.drop_index(
        "ix_mobi_slon_request_logs_created_at",
        table_name="mobi_slon_request_logs",
        schema="seranking",
    )
    op.drop_table("mobi_slon_request_logs", schema="seranking")
    op.drop_index(
        "ix_http_request_logs_request_id",
        table_name="http_request_logs",
        schema="seranking",
    )
    op.drop_index(
        "ix_http_request_logs_created_at",
        table_name="http_request_logs",
        schema="seranking",
    )
    op.drop_table("http_request_logs", schema="seranking")
    # ### end Alembic commands ###
