"""init

Revision ID: 3bf3381ee982
Revises:
Create Date: 2026-02-20 16:33:17.857766

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3bf3381ee982"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_user_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "telegram_user_id", name="uq_access_order_telegram"
        ),
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_access_bindings_order_id"),
        "access_bindings",
        ["order_id"],
        unique=False,
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_access_bindings_telegram_user_id"),
        "access_bindings",
        ["telegram_user_id"],
        unique=False,
        schema="seranking",
    )
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revoked_reason", sa.String(length=128), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_access_tokens_order_id"),
        "access_tokens",
        ["order_id"],
        unique=False,
        schema="seranking",
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("clickid", sa.String(length=128), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("plan", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("fulfillment_status", sa.String(length=32), nullable=False),
        sa.Column("access_status", sa.String(length=32), nullable=False),
        sa.Column("stripe_session_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=128), nullable=True),
        sa.Column(
            "stripe_current_period_end", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_session_id"),
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_orders_email"),
        "orders",
        ["email"],
        unique=False,
        schema="seranking",
    )
    op.create_table(
        "payment_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("stripe_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("process_result", sa.String(length=32), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_payment_events_stripe_event_id"),
        "payment_events",
        ["stripe_event_id"],
        unique=True,
        schema="seranking",
    )
    op.create_table(
        "restore_otps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("otp_hash", sa.String(length=128), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_restore_otps_email"),
        "restore_otps",
        ["email"],
        unique=False,
        schema="seranking",
    )
    op.create_index(
        op.f("ix_seranking_restore_otps_otp_hash"),
        "restore_otps",
        ["otp_hash"],
        unique=False,
        schema="seranking",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_seranking_restore_otps_otp_hash"),
        table_name="restore_otps",
        schema="seranking",
    )
    op.drop_index(
        op.f("ix_seranking_restore_otps_email"),
        table_name="restore_otps",
        schema="seranking",
    )
    op.drop_table("restore_otps", schema="seranking")
    op.drop_index(
        op.f("ix_seranking_payment_events_stripe_event_id"),
        table_name="payment_events",
        schema="seranking",
    )
    op.drop_table("payment_events", schema="seranking")
    op.drop_index(
        op.f("ix_seranking_orders_email"), table_name="orders", schema="seranking"
    )
    op.drop_table("orders", schema="seranking")
    op.drop_index(
        op.f("ix_seranking_access_tokens_order_id"),
        table_name="access_tokens",
        schema="seranking",
    )
    op.drop_table("access_tokens", schema="seranking")
    op.drop_index(
        op.f("ix_seranking_access_bindings_telegram_user_id"),
        table_name="access_bindings",
        schema="seranking",
    )
    op.drop_index(
        op.f("ix_seranking_access_bindings_order_id"),
        table_name="access_bindings",
        schema="seranking",
    )
    op.drop_table("access_bindings", schema="seranking")
    # ### end Alembic commands ###
