import type { AccessStatusCode, Role, SessionMode } from "./types";

export const roleLabels: Record<Role, string> = {
  USER_SELF: "Я писал(а)",
  USER_PEER: "Он·Она писал(а)",
};

export const appCopy = {
  brand: {
    name: "Flirto Guru",
    tagline: "Новая консультация",
  },
  tabs: [
    { to: "/app", label: "Совет" },
    { to: "/paywall", label: "Доступ" },
    { to: "/help", label: "Помощь" },
    { to: "/app/profile", label: "Профиль" },
  ],
  shell: {
    logout: "Выйти",
    boot: "Открываем Flirto Guru...",
    back: "Назад",
    finishSession: "Завершить",
    close: "Закрыть",
    retry: "Повторить",
    themeLight: "Светлая тема",
    themeDark: "Тёмная тема",
  },
  login: {
    eyebrow: "Вход",
    title: "Войти",
    body: "",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    codeLabel: "Код из письма",
    codePlaceholder: "000000",
    requestCode: "Получить код →",
    confirmCode: "Войти →",
    resendCode: "Изменить email",
    emailHint: "",
    requestSuccess: "Код отправлен — проверь почту.",
    requestError: "Не получилось отправить код.",
    confirmError: "Код не подошел.",
  },
  paywall: {
    eyebrow: "Доступ",
    title: "Нужна активация",
    body: "После оплаты вернись сюда — приложение подтянет статус",
    primaryCta: "Открыть оплату",
    bullets: [
      "Доступ привязан к email.",
      "После оплаты не нужно входить заново.",
      "Единый доступ для бота и приложения.",
      "Поддержка поможет если что-то не сработало.",
    ],
    checking: "Проверяем статус доступа...",
  },
  access: {
    grace_period: {
      title: "Продлите доступ",
      body: "Льготный период скоро закончится.",
      cta: "Продлить",
    },
    token_issued: {
      title: "Доступ выпущен",
      body: "Если ты только что оплатил(а), просто открой оплату и вернись обратно.",
      cta: "Открыть доступ",
    },
  } satisfies Partial<Record<AccessStatusCode, { title: string; body: string; cta: string }>>,
  home: {
    eyebrow: "Совет",
    title: "",
    body: "Добавь контекст и получи разбор прямо в чате.",
    opening: "Открываем...",
    startConsultation: "Новая консультация",
    startBody: "Добавь переписку, скриншот или голосовое — получишь разбор, план и текст ответа.",
    startCta: "Новая консультация",
    quickProfile: "Профиль",
    quickSupport: "Поддержка",
    quickHelp: "Помощь",
    pushTitle: "Оповещать, когда ответ готов?",
    pushBody: "Только по важным событиям: готовый ответ, доступ и статус аккаунта.",
    pushEnable: "Включить уведомления",
    pushSkip: "Не сейчас",
    installTitle: "Установите на экран Home",
    installBody: "Так приложение открывается как нативное и не теряется в браузерных вкладках.",
    installAction: "Установить",
    installIos: "На iPhone откройте Share и выберите Add to Home Screen.",
    statusTitle: "Статус доступа",
    statusFallback: "Активен",
    accountTitle: "Аккаунт",
    resetTitle: "Сбросить активные сессии",
    resetBody: "Если осталась незавершенная сессия, закрой её и начни заново.",
    resetCta: "Закрыть сессии",
    resetSuccess: "Активные сессии закрыты.",
    resetEmpty: "Активных сессий не было.",
    resetError: "Не получилось закрыть сессии.",
    recentTitle: "Недавние",
    recentEmptyTitle: "История появится здесь",
    recentEmptyBody: "После завершённых консультаций последние сессии можно будет открыть отсюда.",
    recentFallbackPreview: "Недавно открытая консультация",
    onboardingSkip: "Пропустить",
    onboardingNext: "Далее",
    onboardingStart: "Начать",
    onboardingSteps: [
      {
        title: "Добавь контекст",
        body: "Текст переписки, скриншот или голосовое — бот разберётся с ролями сам",
      },
      {
        title: "Нажми готово",
        body: "Покажем загрузку прямо в чате и соберём ответ без лишних экранов",
      },
      {
        title: "Разбор прямо в чате",
        body: "Главный ответ виден сразу, детали открываются кнопками под сообщением",
      },
    ],
  },
  session: {
    composerPlaceholder: "Опиши ситуацию или вставь переписку…",
    send: "Отправить",
    attach: "Вложение",
    attachImage: "Галерея",
    attachCamera: "Камера",
    attachAudio: "Аудиофайл",
    attachVoice: "Голосовое",
    roleTitle: "Кто отправил сообщение",
    roleHint: "Эти метаданные уйдут вместе с текстом, фото или голосовым.",
    roleName: "Имя автора",
    roleDate: "Дата и время",
    roleApply: "Сохранить",
    batchMore: "+ Ещё",
    batchClose: "Готово",
    batchReady: "фрагментов · Готово к разбору",
    confirmTitle: "Проверь контекст",
    confirmHeading: "Проверь контекст",
    confirmBody: "Быстро проверь, что я правильно понял ситуацию и ничего не пропустил.",
    confirmYes: "Верно →",
    confirmEdit: "Уточнить",
    confirmEditCancel: "Свернуть",
    confirmEditSend: "Отправить",
    confirmEditPlaceholder: "Что добавить или уточнить?",
    generate: "Сгенерировать",
    generateBody: "Собираю разбор",
    generateHintMid: "Формулирую совет…",
    generateHintLate: "Почти готово…",
    resultTitle: "Готовый разбор",
    resultSubtitle: "Главное видно сразу, остальное открывается по кнопкам.",
    refineTitle: "Уточнить ответ",
    refinePlaceholder: "Например: сделай мягче, без вопроса в конце…",
    refineSend: "Применить",
    refinePresets: ["Мягче", "Короче", "Смелее", "Ещё вариант"],
    refineCustom: "Своими словами",
    finish: "Завершить сессию",
    support: "Написать в поддержку",
    thinking: "Анализирую контекст…",
    stageCollect: "Собери контекст",
    stageGenerate: "Собираю ответ",
    emptyChat: "Тут появятся твои сообщения, скриншоты и голосовые.",
    emptyChatTitle: "Добавь контекст",
    emptyChatBody: "Текст, скриншот переписки или голосовое",
    imagePendingTag: "[ИЗОБРАЖЕНИЕ]",
    voicePendingTag: "[ГОЛОСОВОЕ]",
    uploadHint: "Добавь роль и при необходимости дату автора.",
    systemSaved: "Контекст добавлен.",
    systemReady: "Контекст собран.",
    systemRefined: "Ответ обновлен.",
    sceneCollectTitle: "Новая консультация",
    sceneCollectSubtitle: "Разбор ситуации",
    voiceHoldToRecord: "Нажми для записи",
    voiceRecording: "Запись",
    voiceDecodeError: "Не получилось расшифровать голосовое.",
    voiceCancelHint: "Свайп влево для отмены",
    voiceCancelReady: "Отпустите, чтобы отменить",
    microphoneDenied: "Разрешите микрофон в настройках браузера.",
    sessionExitTitle: "Прервать сессию?",
    sessionExitBody: "Незавершенный контекст будет потерян.",
    share: "Поделиться",
    newSession: "Новая сессия",
    copy: "Копировать",
    copied: "Скопировано",
    copyInlineHint: "Главный блок ответа",
    sessionMenu: "Параметры сессии",
    resetSession: "Сбросить сессию",
    bubbleDetails: "Детали фрагмента",
    bubbleActions: "Действия с фрагментом",
    deleteFragment: "Удалить",
    deleteFragmentConfirm: "Удалить фрагмент",
    deleteFragmentCancel: "Отмена",
    deleteFragmentBody: "Фрагмент исчезнет из контекста и больше не попадет в проверку и генерацию.",
    deleteFragmentError: "Не получилось удалить фрагмент.",
    showMore: "Показать больше",
    showLess: "Свернуть",
    resultDetails: "Подробности ответа",
    detailOpen: "Открыть блок",
    loadingTitle: "Собираю ответ",
    loadingBody: "Покажу разбор прямо здесь, как только закончу.",
    cards: {
      primaryMessage: "Сообщение",
      why: "Почему",
      risks: "Риски",
      avoid: "Избегать",
      nextStep: "Следующий шаг",
      simpleVersion: "Простой вариант",
      alternatives: "Альтернативы",
      diagnosis: "Диагноз",
      leverage: "Точка рычага",
      plan24: "План 24ч",
      ifReply: "Если ответит",
      ifNoReply: "Если не ответит",
      template: "Шаблон",
      emptyList: "Пока пусто.",
    },
  },
  support: {
    title: "Поддержка",
    placeholder: "Опиши проблему: доступ, оплата, баг, код входа...",
    submit: "Отправить",
    success: "Ответим через канал поддержки.",
    empty: "Сообщение пустое.",
  },
  profile: {
    title: "Профиль",
    plan: "План",
    status: "Статус",
    endSession: "Завершить активные сессии",
    notifications: "Уведомления",
    notificationsOff: "Выкл",
    manageAccess: "Управление доступом",
    resetSubtitle: "Сбросить незавершённые",
    supportSubtitle: "Доступ, оплата, баги",
    help: "Как это работает",
    account: "Аккаунт",
    assistance: "Помощь",
  },
  offline: {
    title: "Нет соединения",
    body: "Оффлайн-скорлупа открылась, но для продолжения нужен интернет и доступ к аккаунту.",
  },
  staticPages: {
    help: {
      eyebrow: "Помощь",
      title: "Как это работает",
      body: "После входа начни новую консультацию, добавь контекст и получи разбор прямо в чате.",
      cards: [
        { title: "Добавь контекст", body: "Напиши ситуацию, пришли скриншот или голосовое" },
        { title: "Нажми «Готово»", body: "Мы соберём всё в историю и покажем разбор в чате" },
        { title: "Продолжай диалог", body: "Новые сообщения и прошлые ответы учитываются дальше" },
      ],
    },
    premium: {
      eyebrow: "Доступ",
      title: "Один доступ для Telegram и приложения",
      body: "Оплата активирует тот же email во всех поверхностях.",
      cards: [
        { title: "Паритет", body: "Советы и разбор ситуации доступны и в боте, и в приложении." },
        { title: "Возврат после оплаты", body: "После оплаты просто вернись в приложение." },
      ],
    },
  },
  toasts: {
    defaultError: "Что-то пошло не так.",
    sessionRestart: "Сессия потерялась. Начали новую.",
    sessionConflict: "Эта сессия уже недоступна. Начали новую.",
    sessionOwnershipMismatch: "Эта сессия принадлежит другому входу или устарела.",
    startOver: "Начать заново",
    forbidden: "Для этого экрана нужен активный доступ.",
    authExpired: "Сессия входа истекла. Войди снова.",
  },
} as const;

export const modeCopy: Record<SessionMode, { title: string; subtitle: string; accent: string }> = {
  write_now: {
    title: "Новая консультация",
    subtitle: "Быстрый разбор прямо в чате",
    accent: "write_now",
  },
  analyze_case: {
    title: "Новая консультация",
    subtitle: "Диагноз, план и шаблон",
    accent: "analyze_case",
  },
};
